modify post-receive

diff --git a/script/post-receive b/script/post-receive
--- a/script/post-receive
+++ b/script/post-receive
@@ -11,13 +11,15 @@ while read OLDSHA NEWSHA REF ; do
 done
 
 # vars
-GIT_DIR=/home/nodeuser/repos/redoctober.git
-DEPLOY_BASE_PATH=/var/nodeapps/redoctober
+GIT_DIR=/home/nodeuser/repos/roadconditions.git
+DEPLOY_BASE_PATH=/home/nodeuser/apps/roadconditions
 DATESTAMP=$(date +"%Y%m%d%H%M%S")
 RELEASE_PATH="$DEPLOY_BASE_PATH/releases/$DATESTAMP"
 CURRENT_PATH="$DEPLOY_BASE_PATH/current"
 SHARED_PATH="$DEPLOY_BASE_PATH/shared"
+LOG_PATH="$DEPLOY_BASE_PATH/shared/logs"
 PRESTART_URL="http://localhost:7464/isup"
+PIDFILE="$CURRENT_PATH/pid/passenger.pid"
 
 echo "GIT_DIR: $GIT_DIR"
 echo "DEPLOY_BASE_PATH: $DEPLOY_BASE_PATH"
@@ -25,7 +27,6 @@ echo "DATESTAMP: $DATESTAMP"
 echo "RELEASE_PATH: $RELEASE_PATH"
 echo "CURRENT_PATH: $CURRENT_PATH"
 echo "SHARED_PATH: $SHARED_PATH"
-echo "DUMP_FILE: $DUMP_FILE"
 echo "PRESTART_URL: $PRESTART_URL"
 
 # create the release directory
@@ -41,21 +42,31 @@ echo "npm install"
 cd $RELEASE_PATH && npm install || { echo "Error running npm install" ; exit 1; }
 
 # copy config files
-echo "Copy config files"
-cp $SHARED_PATH/config/* $RELEASE_PATH/config || { echo "Error copying config files" ; exit 1; }
+echo "Symlink config files"
+ln -s $SHARED_PATH/config/*.json $RELEASE_PATH/config || { echo "Error symlinking config files" ; exit 1; }
+ln -s $SHARED_PATH/Passengerfile.json $RELEASE_PATH || { echo "Error symlinking Passengerfile"; exit 1; }
 
-# build for production
-echo "webpack -p"
-cd $RELEASE_PATH && /usr/local/bin/webpack -p || { echo "Error running gulp" ; exit 1; }
+# symlink logs & pid
+ln -s $SHARED_PATH/{logs,pid} $RELEASE_PATH || { echo "Error symlinking logs & pid" ; exit 1; }
 
 # move symlink
 echo "Move symlink"
-if [ -L $CURRENT_PATH ] ; then
-    rm $CURRENT_PATH || { echo "Error removing current symlink" ; exit 1; }
-fi
+rm $CURRENT_PATH || { echo "Error removing current symlink" ; exit 1; }
 ln -s $RELEASE_PATH $CURRENT_PATH || { echo "Error making symlink" ; exit 1; }
 
-# restart
-echo "Restart"
-touch $SHARED_PATH/restart.txt || { echo "Error touching restart.txt"; exit 1; }
+# start or restart
+if [ -e "$PIDFILE" ]; then
+  # pidfile exists, so app should be running; try to restart it
+  echo "App running; restarting app"
+  /usr/bin/passenger-config restart-app $DEPLOY_BASE_PATH
+else
+  # pidfile does not exist, so app is not running; start it
+  echo "App not running; starting app"
+  cd $CURRENT_PATH && /usr/bin/passenger start
+fi
+
 curl $PRESTART_URL || { echo "Error hitting $PRESTART_URL" ; exit 1; }
+
+# delete old releases
+echo "Cleaning up old releases"
+cd "$DEPLOY_BASE_PATH/releases" && (ls -t | head -n 5; ls) | sort | uniq -u | xargs rm -rf
